
const $=id=>document.getElementById(id); let jobs=[];
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2500)}
function show(name){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(name).classList.add('active');if(name==='today')load()}
$('addBtn').onclick=()=>show('add');
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmt(t){if(!t)return'';const [h,m]=t.split(':').map(Number);const d=new Date();d.setHours(h,m);return d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
async function api(url,o={}){const r=await fetch(url,{...o,headers:{'Content-Type':'application/json'}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Error');return d}
async function load(){jobs=await api('/api/jobs');render()}
function render(){const w=$('jobs');w.innerHTML='';$('empty').style.display=jobs.length?'none':'block';jobs.forEach(j=>{const e=document.createElement('div');e.className='job';e.innerHTML=`<b>${fmt(j.scheduled_time)} · ${esc(j.scheduled_date)}</b><h3>${esc(j.customer_name)}</h3><p>${esc(j.address)}</p><p>${esc(j.description)}</p><div class="actions"><button class="primary" onclick="onWay(${j.id})">On My Way</button><button onclick="openJob(${j.id})">Open</button><button onclick="directions(${j.id})">Directions</button></div>`;w.appendChild(e)})}
$('jobForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/jobs',{method:'POST',body:JSON.stringify({customerName:$('customerName').value,phone:$('phone').value,address:$('address').value,description:$('description').value,scheduledDate:$('scheduledDate').value,scheduledTime:$('scheduledTime').value,estimatedMinutes:$('estimatedMinutes').value,notes:$('notes').value})});e.target.reset();$('estimatedMinutes').value=60;setDate();show('today');toast('Job saved')}catch(e){toast(e.message)}}
function setDate(){const d=new Date();$('scheduledDate').value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}setDate()
async function onWay(id){try{const r=await api(`/api/jobs/${id}/on-way`,{method:'POST',body:JSON.stringify({etaMinutes:20})});await load();toast(r.sent.demo?'Demo mode: message ready':'On My Way text sent')}catch(e){toast(e.message)}}
async function arrived(id){try{const r=await api(`/api/jobs/${id}/arrived`,{method:'POST',body:'{}'});dlg.close();await load();toast(r.sent.demo?'Demo mode: arrival message ready':'Arrival text sent')}catch(e){toast(e.message)}}
async function completeJob(id){try{await api(`/api/jobs/${id}/complete`,{method:'POST',body:'{}'});dlg.close();await load();toast('Job completed; review request scheduled')}catch(e){toast(e.message)}}
function openJob(id){const j=jobs.find(x=>x.id===id);if(!j)return;$('detail').innerHTML=`<h2>${esc(j.customer_name)}</h2><div class="detail-line">${esc(j.phone)}</div><div class="detail-line">${esc(j.address)}</div><div class="detail-line">${esc(j.description)}</div><p>Status: <b>${esc(j.status)}</b></p><button class="primary" onclick="onWay(${j.id})">Notify On My Way</button> <button onclick="arrived(${j.id})">Arrived</button> <button onclick="completeJob(${j.id})">Complete</button>`;dlg.showModal()}
function directions(id){const j=jobs.find(x=>x.id===id);if(j)window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(j.address)}`,'_blank')}
window.show=show;window.onWay=onWay;window.arrived=arrived;window.completeJob=completeJob;window.openJob=openJob;window.directions=directions;load()
